### ISSUE TITLE
0.18.0: AttributeError: 'module' object has no attribute 'Reporter' 

### ISSUE THREAD

**Issue by mbi** [kmmbvnr/django-jenkins#311]
The same config is working fine with 0.17.0. 
Am I missing something obvious? 

Django 1.7.11

Invocation:
```
python manage.py jenkins --settings=kiwi.settings.test
```

Settings:
```
JENKINS_TASKS = (
    'django_jenkins.tasks.with_coverage',
)
```

```
File "/tmp/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line 
utility.execute() 
File "/tmp/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute 
self.fetch_command(subcommand).run_from_argv(self.argv) 
File "/tmp/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 238, in fetch_command 
klass = load_command_class(app_name, subcommand) 
File "/tmp/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 42, in load_command_class 
return module.Command() 
File "/tmp/.venv/local/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py", line 60, in __init__ 
for module_name in self.get_task_list()] 
AttributeError: 'module' object has no attribute 'Reporter' 
```

**Comment by kmmbvnr** [comment]
delete deprecated in 0.17..0   'django_jenkins.tasks.with_coverage' from jenkins_tasks and use --enable-coverage command line option

**Comment by mbi** [comment]
Alright, thanks. (is this documented somewhere?)

**Comment by kmmbvnr** [comment]
you should get warning about that on django_jenkins 0.17.0 for a while

**Comment by jproffitt** [comment]
Thanks for the info. I never had the warning before though.
