### PR TITLE
Support for coverage 4.0

### LINKED ISSUE #298: Errors with coverage 4.0
Coverage 4.0 is still in beta, but django-jenkins will not work with it. See http://coverage.readthedocs.org/en/latest/changes.html#version-4-0b2-pre-release-22-august-2015 for backward incompatibilities.

In particular, the `'_harvest_data'` attribute. I am getting this error:

    File ".../site-packages/django_jenkins/tasks/with_coverage.py",> line 34, in save
        self.coverage._harvest_data()
    AttributeError: 'Coverage' object has no attribute '_harvest_data'

### PR DESCRIPTION
**Pull request by NotSqrt**
Works with coverage 4.0b2

Fixes #298

### CODE REVIEW

**Comment by kmmbvnr** [comment]
Thanks
