### ISSUE TITLE
with_coverage does not work in version 0.18

### ISSUE THREAD

**Issue by jproffitt** [kmmbvnr/django-jenkins#313]
It looks like each task needs to have a `Reporter` class, and the `Reporter` class for `with_coverage` seems to have been removed in 0.18. So I am getting this error:

    File ".../django_jenkins/management/commands/jenkins.py", line 60, in __init__
       for module_name in self.get_task_list()]    
    AttributeError: 'module' object has no attribute 'Reporter'

**Comment by kmmbvnr** [comment]
https://github.com/kmmbvnr/django-jenkins/issues/311
